name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        npm install
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Run deploy.sh
      run: ./deploy.sh